
    CREATE TABLE VERSIONED_ANALYSIS (
        "IDENTITY"          VARCHAR(50)     NOT NULL,
        ANALYSIS_VERSION    BIGINT          NOT NULL,
        ANALYSIS_ORDER      BIGINT,
        GROUP_ID            VARCHAR(50),
        ANALYSIS_TYPE       VARCHAR(50),
        DESCRIPTION         VARCHAR(200),
        INSTTYPE_ID         VARCHAR(50),
        PREPARATION_ID      VARCHAR(50),
        EXPECTED_TIME       VARCHAR(50),
        CHARGECODE          VARCHAR(50),
        RESULT_SCREEN       VARCHAR(50),
        MODIFIED_ON         VARCHAR(20),
        MODIFIED_BY         VARCHAR(50),
        MODIFIABLE          CHAR(1),
        REMOVEFLAG          CHAR(1),
        CALCULATION         VARCHAR(500),
        REPLICATES          BIGINT,
        ACCESS_FLAGS        BIGINT,
        COMP_REPLICATES     BIGINT,
        GENERIC_ANALYSIS    CHAR(1),
        APPROVAL_REQD       CHAR(1),
        ALLOW_CATEGORY      CHAR(1),
        APPROVAL_STATUS     CHAR(1),
        INSPECTION_PLAN     VARCHAR(50),
        SAMPLING_PLAN_TYPE  VARCHAR(50),
        AUTO_VALIDATE       CHAR(1),
        SHIPPING_FLAG       CHAR(1),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_VERSIONED_ANALYSIS PRIMARY KEY ("IDENTITY", ANALYSIS_VERSION)
    );


    CREATE TABLE VERSIONED_COMPONENT (
        NAME                VARCHAR(100)    NOT NULL,
        ANALYSIS            VARCHAR(50)     NOT NULL,
        ANALYSIS_VERSION    BIGINT          NOT NULL,
        ORDER_NUMBER        BIGINT,
        RESULT_TYPE         VARCHAR(50),
        UNITS               VARCHAR(50),
        MINIMUM             VARCHAR(50),
        MAXIMUM             VARCHAR(50),
        TRUE_WORD           VARCHAR(50),
        FALSE_WORD          VARCHAR(50),
        ALLOWED_CHARACTERS  VARCHAR(200),
        CALCULATION         VARCHAR(500),
        PLACES              BIGINT,
        REP_CONTROL         VARCHAR(50),
        REPLICATES          VARCHAR(10),
        SIG_FIGS_NUMBER     BIGINT,
        SIG_FIGS_ROUNDING   VARCHAR(50),
        SIG_FIGS_FILTER     VARCHAR(50),
        MINIMUM_PQL         VARCHAR(50),
        MAXIMUM_PQL         VARCHAR(50),
        PQL_CALCULATION     VARCHAR(500),
        FORMULA             VARCHAR(500),
        MATRIX_NO           BIGINT,
        MATRIX_NAME         VARCHAR(50),
        COLUMN_NO           BIGINT,
        COLUMN_NAME         VARCHAR(50),
        ROW_NO              BIGINT,
        ROW_NAME            VARCHAR(50),
        DESCRIPTION         VARCHAR(200),
        DESCRIPTION_CERQFRA VARCHAR(200),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_VERSIONED_COMPONENT PRIMARY KEY (NAME, ANALYSIS, ANALYSIS_VERSION),
        CONSTRAINT FK_VCOMP_VERSIONED_ANALYSIS FOREIGN KEY (ANALYSIS, ANALYSIS_VERSION)
            REFERENCES VERSIONED_ANALYSIS ("IDENTITY", ANALYSIS_VERSION)
    );

    CREATE TABLE MLP_HEADER (
        "IDENTITY"      VARCHAR(50)     NOT NULL,
        PRODUCT_GROUP   VARCHAR(50),
        DESCRIPTION     VARCHAR(200),
        TEST_SCHEDULE   VARCHAR(50),
        PRODUCT_STATUS  VARCHAR(50),
        MODIFIED_ON     VARCHAR(20),
        MODIFIED_BY     VARCHAR(50),
        MODIFIABLE      CHAR(1),
        REMOVEFLAG      CHAR(1),
        GROUP_ID        VARCHAR(50),
        PRODUCT_VERSION BIGINT          NOT NULL,
        VERSION_COMMENT VARCHAR(200),
        VERSION_STATUS  VARCHAR(50),
        CREATED_DATE    VARCHAR(20),
        APPROVAL_REQD   CHAR(1),
        APPROVAL_STATUS CHAR(1),
        INSPECTION_PLAN VARCHAR(50),
        DUREE_ARCHI     VARCHAR(50),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_MLP_HEADER PRIMARY KEY ("IDENTITY", PRODUCT_VERSION)
    );

    CREATE TABLE SAMPLE (
        ID_NUMERIC          BIGINT          NOT NULL,
        ID_TEXT             VARCHAR(50),
        JOB_NAME            VARCHAR(100),
        STATUS              CHAR(1),
        OLD_STATUS          CHAR(1),
        COMPARED            CHAR(1),
        ON_SPEC             CHAR(1),
        RE_SAMPLED          CHAR(1),
        ORIGINAL_SAMPLE     BIGINT,
        LINK_NUMBER         BIGINT,
        LOGIN_DATE          VARCHAR(20),
        LOGIN_BY            VARCHAR(50),
        SAMPLED_DATE        VARCHAR(20),
        RECD_DATE           VARCHAR(20),
        DATE_STARTED        VARCHAR(20),
        STARTER             VARCHAR(50),
        DATERESREQ          VARCHAR(20),
        DATE_COMPLETED      VARCHAR(20),
        COMPLETER           VARCHAR(50),
        DATERESAVAIL        VARCHAR(20),
        DATE_AUTHORISED     VARCHAR(20),
        AUTHORISER          VARCHAR(50),
        AUTHORISATION_NOTES VARCHAR(500),
        PRODUCT             VARCHAR(50),
        PRODUCT_VERSION     BIGINT,
        GRADE_CODE          VARCHAR(50),
        TESTS_TO_DO         BIGINT,
        ON_WKS              CHAR(1),
        PROJECT_ID          VARCHAR(50),
        BATCH_NAME          VARCHAR(100),
        SAMPLING_POINT      VARCHAR(50),
        SAMPLE_TYPE         VARCHAR(50),
        SAMPLE_NAME         VARCHAR(100),
        DESCRIPTION         VARCHAR(500),
        PREPARATION         VARCHAR(100),
        HAZARD              VARCHAR(100),
        PRIORITY            BIGINT,
        LOCATION_ID         VARCHAR(50),
        CUSTOMER_ID         VARCHAR(50),
        INVOICE_NUMBER      VARCHAR(50),
        TEST_SCHEDULE       VARCHAR(50),
        TEMPLATE_ID         VARCHAR(50),
        COMP_PROD_NAME      VARCHAR(100),
        COMP_PROD_VER       BIGINT,
        COMP_PROD_GRADE     VARCHAR(50),
        STANDARD            VARCHAR(50),
        STANDARD_ID         VARCHAR(50),
        STANDARD_VERSION    BIGINT,
        INSPECTION_HEADER   VARCHAR(50),
        STANDARD_TYPE       VARCHAR(50),
        BATCH_ID            VARCHAR(50),
        DYNAMIC_PRODUCT     VARCHAR(50),
        TOTAL_ELEMENTS      BIGINT,
        SAMPLING_PROCEDURE  VARCHAR(50),
        REPLICATE_LINK_NO   BIGINT,
        AUTO_VALIDATE       CHAR(1),
        HAS_INCIDENTS       CHAR(1),
        CODE_CONTROLE       VARCHAR(50),
        CONDITIONNEMENT     VARCHAR(50),
        DESTINATION_MATIERE VARCHAR(50),
        FOURNISSEUR         VARCHAR(50),
        NUM_LOT             VARCHAR(50),
        PRELEVEUR           VARCHAR(50),
        DUREE_STOCKAGE      VARCHAR(50),
        SAMPLE_AUTO         CHAR(1),
        INDEX_POLAB         VARCHAR(50),
        NUM_POLAB           VARCHAR(50),
        COMMENTAIRES        VARCHAR(500),
        LOT_AN              VARCHAR(50),
        GROUP_ID            VARCHAR(50),
        ANALYSE_AUTO        CHAR(1),
        DATE_PREL_VP        VARCHAR(20),
        TONNAGE             VARCHAR(50),
        PLT_NUMBER_FROM     VARCHAR(20),
        PLT_NUMBER_TO       VARCHAR(20),
        UNIT_TYPE           VARCHAR(50),
        PLT_NUMBER          VARCHAR(20),
        LAF_BATCH           VARCHAR(50),
        DATE_SHIPPED        VARCHAR(20),
        PACKAGE             VARCHAR(50),
        SHIPPING            VARCHAR(50),
        SHIP_USR            VARCHAR(50),
        COQ                 CHAR(1),
        SUBMIT_SHIP         CHAR(1),
        PRODUIT_QUALIFIE    VARCHAR(50),
        GRANULOMETRIE       VARCHAR(50),
        REF_LIVRAISON       VARCHAR(50),
        DATE_LIVRAISON      VARCHAR(20),
        LOT_FOURNISSEUR     VARCHAR(50),
        TAS_STOCKAGE        VARCHAR(50),
        "FORMAT"            VARCHAR(50),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_SAMPLE PRIMARY KEY (ID_NUMERIC)
    );


    CREATE TABLE SAMPLE_POINT (
        "IDENTITY"      VARCHAR(50)     NOT NULL,
        GROUP_ID        VARCHAR(50),
        POINT_LOCATION  VARCHAR(50),
        SAMPLE_TYPE     VARCHAR(50),
        DESCRIPTION     VARCHAR(200),
        MODIFIED_ON     VARCHAR(20),
        MODIFIED_BY     VARCHAR(50),
        MODIFIABLE      CHAR(1),
        REMOVEFLAG      CHAR(1),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_SAMPLE_POINT PRIMARY KEY ("IDENTITY")
    );

    CREATE TABLE CUSTOMER (
        "IDENTITY"      VARCHAR(50)     NOT NULL,
        GROUP_ID        VARCHAR(50),
        COMPANY_NAME    VARCHAR(200),
        ADDRESS1        VARCHAR(100),
        ADDRESS2        VARCHAR(100),
        ADDRESS3        VARCHAR(100),
        ADDRESS4        VARCHAR(100),
        ADDRESS5        VARCHAR(100),
        ADDRESS6        VARCHAR(100),
        PHONE_NUM       VARCHAR(50),
        CONTACT         VARCHAR(100),
        MODIFIED_ON     VARCHAR(20),
        MODIFIED_BY     VARCHAR(50),
        MODIFIABLE      CHAR(1),
        REMOVEFLAG      CHAR(1),
        SUSPENDFLAG     CHAR(1),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_CUSTOMER PRIMARY KEY ("IDENTITY")
    );

    CREATE TABLE "LOCATION" (
        "IDENTITY"      VARCHAR(50)     NOT NULL,
        GROUP_ID        VARCHAR(50),
        DESCRIPTION     VARCHAR(200),
        MODIFIED_ON     VARCHAR(20),
        MODIFIED_BY     VARCHAR(50),
        MODIFIABLE      CHAR(1),
        REMOVEFLAG      CHAR(1),
        ORDER_NUMBER    BIGINT,
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_LOCATION PRIMARY KEY ("IDENTITY")
    );


    CREATE TABLE CODE_CONTROLE (
        "IDENTITY"          VARCHAR(50)     NOT NULL,
        GROUP_ID            VARCHAR(50),
        DESCRIPTION         VARCHAR(200),
        PRODUIT             VARCHAR(50),
        ORIGINE_MATIERE     VARCHAR(50),
        POINT_PRELEVEMENT   VARCHAR(50),
        CODE_MAT_POLAB      VARCHAR(50),
        MODIFIED_ON         VARCHAR(20),
        MODIFIED_BY         VARCHAR(50),
        MODIFIABLE          CHAR(1),
        REMOVEFLAG          CHAR(1),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_CODE_CONTROLE PRIMARY KEY ("IDENTITY")
    );

    CREATE TABLE FOURNISSEUR (
        "IDENTITY"      VARCHAR(50)     NOT NULL,
        GROUP_ID        VARCHAR(50),
        COMPANY_NAME    VARCHAR(200),
        CONTACT         VARCHAR(100),
        TELEPHONE       VARCHAR(50),
        ADDRESS1        VARCHAR(100),
        ADDRESS2        VARCHAR(100),
        ADDRESS3        VARCHAR(100),
        ADDRESS4        VARCHAR(100),
        MODIFIED_ON     VARCHAR(20),
        MODIFIED_BY     VARCHAR(50),
        MODIFIABLE      CHAR(1),
        REMOVEFLAG      CHAR(1),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_FOURNISSEUR PRIMARY KEY ("IDENTITY")
    );

    CREATE TABLE JOB_HEADER (
        JOB_NAME            VARCHAR(100)    NOT NULL,
        JOB_STATUS          CHAR(1),
        BROWSE_DESCRIPTION  VARCHAR(200),
        SAMPLE_SYNTAX_ID    VARCHAR(50),
        DATE_CREATED        VARCHAR(20),
        DATE_COMPLETED      VARCHAR(20),
        DATE_RECEIVED       VARCHAR(20),
        DATE_TO_START       VARCHAR(20),
        SUBMITTER_OPER      VARCHAR(50),
        SAMPLES_TO_DO       BIGINT,
        GROUP_ID            VARCHAR(50),
        TEMPLATE_ID         VARCHAR(50),
        SAMPLE_TEMPLATE     VARCHAR(50),
        DATE_AUTHORISED     VARCHAR(20),
        AUTHORISER          VARCHAR(50),
        AUTHORISATION_NOTES VARCHAR(500),
        OLD_STATUS          CHAR(1),
        INSPECTION_HEADER   VARCHAR(50),
        NODE_TRIGGER_PATH   VARCHAR(200),
        ORIGINAL_JOB        VARCHAR(100),
        BEEN_COPIED         CHAR(1),
        AUTO_VALIDATE       CHAR(1),
        TOTAL_ELEMENTS      BIGINT,
        LOT_ID              VARCHAR(50),
        LOT_NUMBER          VARCHAR(50),
        BAD_PALLETS         BIGINT,
        QTY_AVAILBLE        BIGINT,
        FOURNISSEUR         VARCHAR(50),
        GRANULOMETRIE       VARCHAR(50),
        REF_LIVRAISON       VARCHAR(50),
        DATE_LIVRAISON      VARCHAR(20),
        TONNAGE             VARCHAR(50),
        LOT_FOURNISSEUR     VARCHAR(50),
        TAS_STOCKAGE        VARCHAR(50),
        "FORMAT"            VARCHAR(50),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_JOB_HEADER PRIMARY KEY (JOB_NAME)
    );

    CREATE TABLE PHRASE (
        PHRASE_ID       VARCHAR(50)     NOT NULL,
        PHRASE_TYPE     VARCHAR(20)     NOT NULL,
        ORDER_NUM       BIGINT,
        PHRASE_TEXT     VARCHAR(500),
        ICON            VARCHAR(100),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_PHRASE PRIMARY KEY (PHRASE_ID)
    );


    CREATE TABLE MENSUEL (
        IDENT_NUMBER        BIGINT,
        ID_DATE             VARCHAR(20),
        CODE_CONTROLE       VARCHAR(50),
        PRODUIT             VARCHAR(50)     NOT NULL,
        PRODUCT_VERSION     BIGINT          NOT NULL,
        LOCALISATION        VARCHAR(50)     NOT NULL,
        POINT_PRELEVEMENT   VARCHAR(50),
        "ANALYSE"           VARCHAR(50)     NOT NULL,
        MESURE              VARCHAR(100)    NOT NULL,
        ANNUEL              CHAR(1)         NOT NULL,
        NB_MESURE           BIGINT,
        MOYENNE             VARCHAR(50),
        ECART_TYPE          VARCHAR(50),
        ECART_TYPE_BDQ      VARCHAR(50),
        SPEC_MIN            VARCHAR(50),
        SPEC_MAX            VARCHAR(50),
        CIBLE               VARCHAR(50),
        GROUP_ID            VARCHAR(50),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_MENSUEL PRIMARY KEY ("ANALYSE", PRODUIT, PRODUCT_VERSION, MESURE, LOCALISATION),

        CONSTRAINT FK_MENSUEL_LOCATION FOREIGN KEY (LOCALISATION)
            REFERENCES "LOCATION" ("IDENTITY"),
        CONSTRAINT FK_MENSUEL_CODE_CONTROLE FOREIGN KEY (CODE_CONTROLE)
            REFERENCES CODE_CONTROLE ("IDENTITY")
    );

    -- ------------------------------------------------------------------------
    -- SAMP_TEST_RESULT_LAFA / C_SAMP_TEST_RESULT_LAFA
    -- Flat denormalized fact tables (one row per result per component per test
    -- per sample). Columns match the actual source extract header exactly
    -- (81 data columns), including the source typo TES_ON_SPEC.
    -- RESULT_VALUE / RESULT_TEXT / MINIMUM / MAXIMUM are VARCHAR (decimals).
    -- ------------------------------------------------------------------------
    CREATE TABLE SAMP_TEST_RESULT_LAFA (
        ID_NUMERIC              BIGINT,
        ID_TEXT                 VARCHAR(100),
        STATUS                  CHAR(1),
        CUSTOMER_ID             VARCHAR(50),
        FOURNISSEUR             VARCHAR(50),
        PRODUCT                 VARCHAR(50),
        PRODUCT_VERSION         BIGINT,
        COMMENTAIRES            VARCHAR(500),
        LOGIN_BY                VARCHAR(50),
        LOGIN_DATE              VARCHAR(20),
        SAMPLED_DATE            VARCHAR(20),
        DUREE_STOCKAGE          VARCHAR(50),
        CONDITIONNEMENT         VARCHAR(50),
        NUM_LOT                 VARCHAR(50),
        ON_SPEC                 CHAR(1),
        DATE_PREL_VP            VARCHAR(20),
        LOCATION_ID             VARCHAR(50),
        DESTINATION_MATIERE     VARCHAR(50),
        CODE_CONTROLE           VARCHAR(50),
        SAMPLING_POINT          VARCHAR(50),
        LOT_AN                  VARCHAR(50),
        ORIGINAL_SAMPLE         BIGINT,
        TEST_SCHEDULE           VARCHAR(50),
        JOB_NAME                VARCHAR(100),
        OLD_STATUS              CHAR(1),
        RECD_DATE               VARCHAR(20),
        DATE_STARTED            VARCHAR(20),
        DATERESREQ              VARCHAR(20),
        DATE_COMPLETED          VARCHAR(20),
        COMPLETER               VARCHAR(50),
        DATERESAVAIL            VARCHAR(20),
        TESTS_TO_DO             BIGINT,
        BATCH_NAME              VARCHAR(100),
        SAMPLE_TYPE             VARCHAR(50),
        SAMPLE_NAME             VARCHAR(100),
        DESCRIPTION             VARCHAR(500),
        PREPARATION             VARCHAR(100),
        STANDARD                VARCHAR(50),
        BATCH_ID                VARCHAR(50),
        HAS_INCIDENTS           CHAR(1),
        PRELEVEUR               VARCHAR(50),
        SAMPLE_AUTO             CHAR(1),
        ANALYSE_AUTO            CHAR(1),
        TONNAGE                 VARCHAR(50),
        UNIT_TYPE               VARCHAR(50),
        COQ                     CHAR(1),
        PRODUIT_QUALIFIE        VARCHAR(50),
        GRANULOMETRIE           VARCHAR(50),
        REF_LIVRAISON           VARCHAR(50),
        DATE_LIVRAISON          VARCHAR(20),
        "FORMAT"                VARCHAR(50),
        TEST_NUMBER             BIGINT,
        TEST_COUNT              BIGINT,
        REPLICATE_TEST          CHAR(1),
        ANALYSIS                VARCHAR(50),
        TEST_STATUS             CHAR(1),
        TECHNICIEN              VARCHAR(50),
        TEST_DATE_STARTED       VARCHAR(20),
        TEST_DATE_COMPLETED     VARCHAR(20),
        INSTRUMENT              VARCHAR(50),
        TES_ON_SPEC             CHAR(1),
        ORDER_NUM               BIGINT,
        VALIDATION_STATUS       VARCHAR(50),
        AUTHORISATION_COMMENT   VARCHAR(500),
        TEST_HAS_INCIDENTS      CHAR(1),
        ANALYSIS_VERSION        BIGINT,
        COMPONENT_NAME          VARCHAR(100),
        RESULT_TYPE             VARCHAR(50),
        RESULT_STATUS           CHAR(1),
        RESULT_TEXT             VARCHAR(200),
        RESULT_VALUE            VARCHAR(50),
        UNITS                   VARCHAR(50),
        MINIMUM                 VARCHAR(50),
        MAXIMUM                 VARCHAR(50),
        OUT_OF_RANGE            CHAR(1),
        DATE_RESULT_ENTERED     VARCHAR(20),
        RESULT_ENTERED_BY       VARCHAR(50),
        ORDER_NUMBER_BY         BIGINT,
        TYPICAL                 VARCHAR(50),
        CALCULATION             VARCHAR(500),
        PLACES                  BIGINT,
        SOURCE                  VARCHAR(10),
        LAST_UPDATED_AT         TIMESTAMP,
        CONSTRAINT FK_STRL_MLP_HEADER FOREIGN KEY (PRODUCT, PRODUCT_VERSION)
            REFERENCES MLP_HEADER ("IDENTITY", PRODUCT_VERSION),
        CONSTRAINT FK_STRL_SAMPLE_POINT FOREIGN KEY (SAMPLING_POINT)
            REFERENCES SAMPLE_POINT ("IDENTITY"),
        CONSTRAINT FK_STRL_LOCATION FOREIGN KEY (LOCATION_ID)
            REFERENCES "LOCATION" ("IDENTITY"),
        CONSTRAINT FK_STRL_CODE_CONTROLE FOREIGN KEY (CODE_CONTROLE)
            REFERENCES CODE_CONTROLE ("IDENTITY"),
        CONSTRAINT FK_STRL_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER ("IDENTITY"),
        CONSTRAINT FK_STRL_FOURNISSEUR FOREIGN KEY (FOURNISSEUR)
            REFERENCES FOURNISSEUR ("IDENTITY"),
        CONSTRAINT FK_STRL_SAMPLE FOREIGN KEY (ORIGINAL_SAMPLE)
            REFERENCES SAMPLE (ID_NUMERIC),
        CONSTRAINT FK_STRL_JOB_HEADER FOREIGN KEY (JOB_NAME)
            REFERENCES JOB_HEADER (JOB_NAME),
        CONSTRAINT FK_STRL_PHRASE FOREIGN KEY (GRANULOMETRIE)
            REFERENCES PHRASE (PHRASE_ID)
    );

    CREATE TABLE C_SAMP_TEST_RESULT_LAFA (
        ID_NUMERIC              BIGINT,
        ID_TEXT                 VARCHAR(100),
        STATUS                  CHAR(1),
        CUSTOMER_ID             VARCHAR(50),
        FOURNISSEUR             VARCHAR(50),
        PRODUCT                 VARCHAR(50),
        PRODUCT_VERSION         BIGINT,
        COMMENTAIRES            VARCHAR(500),
        LOGIN_BY                VARCHAR(50),
        LOGIN_DATE              VARCHAR(20),
        SAMPLED_DATE            VARCHAR(20),
        DUREE_STOCKAGE          VARCHAR(50),
        CONDITIONNEMENT         VARCHAR(50),
        NUM_LOT                 VARCHAR(50),
        ON_SPEC                 CHAR(1),
        DATE_PREL_VP            VARCHAR(20),
        LOCATION_ID             VARCHAR(50),
        DESTINATION_MATIERE     VARCHAR(50),
        CODE_CONTROLE           VARCHAR(50),
        SAMPLING_POINT          VARCHAR(50),
        LOT_AN                  VARCHAR(50),
        ORIGINAL_SAMPLE         BIGINT,
        TEST_SCHEDULE           VARCHAR(50),
        JOB_NAME                VARCHAR(100),
        OLD_STATUS              CHAR(1),
        RECD_DATE               VARCHAR(20),
        DATE_STARTED            VARCHAR(20),
        DATERESREQ              VARCHAR(20),
        DATE_COMPLETED          VARCHAR(20),
        COMPLETER               VARCHAR(50),
        DATERESAVAIL            VARCHAR(20),
        TESTS_TO_DO             BIGINT,
        BATCH_NAME              VARCHAR(100),
        SAMPLE_TYPE             VARCHAR(50),
        SAMPLE_NAME             VARCHAR(100),
        DESCRIPTION             VARCHAR(500),
        PREPARATION             VARCHAR(100),
        STANDARD                VARCHAR(50),
        BATCH_ID                VARCHAR(50),
        HAS_INCIDENTS           CHAR(1),
        PRELEVEUR               VARCHAR(50),
        SAMPLE_AUTO             CHAR(1),
        ANALYSE_AUTO            CHAR(1),
        TONNAGE                 VARCHAR(50),
        UNIT_TYPE               VARCHAR(50),
        COQ                     CHAR(1),
        PRODUIT_QUALIFIE        VARCHAR(50),
        GRANULOMETRIE           VARCHAR(50),
        REF_LIVRAISON           VARCHAR(50),
        DATE_LIVRAISON          VARCHAR(20),
        "FORMAT"                VARCHAR(50),
        TEST_NUMBER             BIGINT,
        TEST_COUNT              BIGINT,
        REPLICATE_TEST          CHAR(1),
        ANALYSIS                VARCHAR(50),
        TEST_STATUS             CHAR(1),
        TECHNICIEN              VARCHAR(50),
        TEST_DATE_STARTED       VARCHAR(20),
        TEST_DATE_COMPLETED     VARCHAR(20),
        INSTRUMENT              VARCHAR(50),
        TES_ON_SPEC             CHAR(1),
        ORDER_NUM               BIGINT,
        VALIDATION_STATUS       VARCHAR(50),
        AUTHORISATION_COMMENT   VARCHAR(500),
        TEST_HAS_INCIDENTS      CHAR(1),
        ANALYSIS_VERSION        BIGINT,
        COMPONENT_NAME          VARCHAR(100),
        RESULT_TYPE             VARCHAR(50),
        RESULT_STATUS           CHAR(1),
        RESULT_TEXT             VARCHAR(200),
        RESULT_VALUE            VARCHAR(50),
        UNITS                   VARCHAR(50),
        MINIMUM                 VARCHAR(50),
        MAXIMUM                 VARCHAR(50),
        OUT_OF_RANGE            CHAR(1),
        DATE_RESULT_ENTERED     VARCHAR(20),
        RESULT_ENTERED_BY       VARCHAR(50),
        ORDER_NUMBER_BY         BIGINT,
        TYPICAL                 VARCHAR(50),
        CALCULATION             VARCHAR(500),
        PLACES                  BIGINT,
        SOURCE                  VARCHAR(10),
        LAST_UPDATED_AT         TIMESTAMP,
        CONSTRAINT FK_CSTRL_MLP_HEADER FOREIGN KEY (PRODUCT, PRODUCT_VERSION)
            REFERENCES MLP_HEADER ("IDENTITY", PRODUCT_VERSION),
        CONSTRAINT FK_CSTRL_SAMPLE_POINT FOREIGN KEY (SAMPLING_POINT)
            REFERENCES SAMPLE_POINT ("IDENTITY"),
        CONSTRAINT FK_CSTRL_LOCATION FOREIGN KEY (LOCATION_ID)
            REFERENCES "LOCATION" ("IDENTITY"),
        CONSTRAINT FK_CSTRL_CODE_CONTROLE FOREIGN KEY (CODE_CONTROLE)
            REFERENCES CODE_CONTROLE ("IDENTITY"),
        CONSTRAINT FK_CSTRL_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER ("IDENTITY"),
        CONSTRAINT FK_CSTRL_FOURNISSEUR FOREIGN KEY (FOURNISSEUR)
            REFERENCES FOURNISSEUR ("IDENTITY"),
        CONSTRAINT FK_CSTRL_SAMPLE FOREIGN KEY (ORIGINAL_SAMPLE)
            REFERENCES SAMPLE (ID_NUMERIC),
        CONSTRAINT FK_CSTRL_JOB_HEADER FOREIGN KEY (JOB_NAME)
            REFERENCES JOB_HEADER (JOB_NAME),
        CONSTRAINT FK_CSTRL_PHRASE FOREIGN KEY (GRANULOMETRIE)
            REFERENCES PHRASE (PHRASE_ID)
    );

    CREATE TABLE C_SAMPLE (
        ID_NUMERIC          BIGINT          NOT NULL,
        ID_TEXT             VARCHAR(50),
        JOB_NAME            VARCHAR(100),
        STATUS              CHAR(1),
        OLD_STATUS          CHAR(1),
        COMPARED            CHAR(1),
        ON_SPEC             CHAR(1),
        RE_SAMPLED          CHAR(1),
        ORIGINAL_SAMPLE     BIGINT,
        LINK_NUMBER         BIGINT,
        LOGIN_DATE          VARCHAR(20),
        LOGIN_BY            VARCHAR(50),
        SAMPLED_DATE        VARCHAR(20),
        RECD_DATE           VARCHAR(20),
        DATE_STARTED        VARCHAR(20),
        STARTER             VARCHAR(50),
        DATERESREQ          VARCHAR(20),
        DATE_COMPLETED      VARCHAR(20),
        COMPLETER           VARCHAR(50),
        DATERESAVAIL        VARCHAR(20),
        DATE_AUTHORISED     VARCHAR(20),
        AUTHORISER          VARCHAR(50),
        AUTHORISATION_NOTES VARCHAR(500),
        PRODUCT             VARCHAR(50),
        PRODUCT_VERSION     BIGINT,
        GRADE_CODE          VARCHAR(50),
        TESTS_TO_DO         BIGINT,
        ON_WKS              CHAR(1),
        PROJECT_ID          VARCHAR(50),
        BATCH_NAME          VARCHAR(100),
        SAMPLING_POINT      VARCHAR(50),
        SAMPLE_TYPE         VARCHAR(50),
        SAMPLE_NAME         VARCHAR(100),
        DESCRIPTION         VARCHAR(500),
        PREPARATION         VARCHAR(100),
        HAZARD              VARCHAR(100),
        PRIORITY            BIGINT,
        LOCATION_ID         VARCHAR(50),
        CUSTOMER_ID         VARCHAR(50),
        INVOICE_NUMBER      VARCHAR(50),
        TEST_SCHEDULE       VARCHAR(50),
        TEMPLATE_ID         VARCHAR(50),
        COMP_PROD_NAME      VARCHAR(100),
        COMP_PROD_VER       BIGINT,
        COMP_PROD_GRADE     VARCHAR(50),
        STANDARD            VARCHAR(50),
        STANDARD_ID         VARCHAR(50),
        STANDARD_VERSION    BIGINT,
        INSPECTION_HEADER   VARCHAR(50),
        STANDARD_TYPE       VARCHAR(50),
        BATCH_ID            VARCHAR(50),
        DYNAMIC_PRODUCT     VARCHAR(50),
        TOTAL_ELEMENTS      BIGINT,
        SAMPLING_PROCEDURE  VARCHAR(50),
        REPLICATE_LINK_NO   BIGINT,
        AUTO_VALIDATE       CHAR(1),
        HAS_INCIDENTS       CHAR(1),
        CODE_CONTROLE       VARCHAR(50),
        CONDITIONNEMENT     VARCHAR(50),
        DESTINATION_MATIERE VARCHAR(50),
        FOURNISSEUR         VARCHAR(50),
        NUM_LOT             VARCHAR(50),
        PRELEVEUR           VARCHAR(50),
        DUREE_STOCKAGE      VARCHAR(50),
        SAMPLE_AUTO         CHAR(1),
        INDEX_POLAB         VARCHAR(50),
        NUM_POLAB           VARCHAR(50),
        COMMENTAIRES        VARCHAR(500),
        LOT_AN              VARCHAR(50),
        GROUP_ID            VARCHAR(50),
        ANALYSE_AUTO        CHAR(1),
        DATE_PREL_VP        VARCHAR(20),
        TONNAGE             VARCHAR(50),
        PLT_NUMBER_FROM     VARCHAR(20),
        PLT_NUMBER_TO       VARCHAR(20),
        UNIT_TYPE           VARCHAR(50),
        PLT_NUMBER          VARCHAR(20),
        LAF_BATCH           VARCHAR(50),
        DATE_SHIPPED        VARCHAR(20),
        PACKAGE             VARCHAR(50),
        SHIPPING            VARCHAR(50),
        SHIP_USR            VARCHAR(50),
        COQ                 CHAR(1),
        SUBMIT_SHIP         CHAR(1),
        PRODUIT_QUALIFIE    VARCHAR(50),
        GRANULOMETRIE       VARCHAR(50),
        REF_LIVRAISON       VARCHAR(50),
        DATE_LIVRAISON      VARCHAR(20),
        LOT_FOURNISSEUR     VARCHAR(50),
        TAS_STOCKAGE        VARCHAR(50),
        "FORMAT"            VARCHAR(50),
        SOURCE              VARCHAR(10),
        LAST_UPDATED_AT     TIMESTAMP,
        CONSTRAINT PK_C_SAMPLE PRIMARY KEY (ID_NUMERIC),
        CONSTRAINT FK_CSAMPLE_JOB_HEADER FOREIGN KEY (JOB_NAME)
            REFERENCES JOB_HEADER (JOB_NAME),
        CONSTRAINT FK_CSAMPLE_SAMPLE_POINT FOREIGN KEY (SAMPLING_POINT)
            REFERENCES SAMPLE_POINT ("IDENTITY"),
        CONSTRAINT FK_CSAMPLE_MLP_HEADER FOREIGN KEY (PRODUCT, PRODUCT_VERSION)
            REFERENCES MLP_HEADER ("IDENTITY", PRODUCT_VERSION),
        CONSTRAINT FK_CSAMPLE_LOCATION FOREIGN KEY (LOCATION_ID)
            REFERENCES "LOCATION" ("IDENTITY"),
        CONSTRAINT FK_CSAMPLE_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER ("IDENTITY"),
        CONSTRAINT FK_CSAMPLE_FOURNISSEUR FOREIGN KEY (FOURNISSEUR)
            REFERENCES FOURNISSEUR ("IDENTITY"),
        CONSTRAINT FK_CSAMPLE_CODE_CONTROLE FOREIGN KEY (CODE_CONTROLE)
            REFERENCES CODE_CONTROLE ("IDENTITY"),
        CONSTRAINT FK_CSAMPLE_PHRASE FOREIGN KEY (GRANULOMETRIE)
            REFERENCES PHRASE (PHRASE_ID)
    );

    CREATE TABLE MLP_VIEW (
        ANALYSIS_ID     VARCHAR(50)     NOT NULL,
        COMPONENT_NAME  VARCHAR(100)    NOT NULL,
        PRODUCT_ID      VARCHAR(50)     NOT NULL,
        PRODUCT_VERSION BIGINT          NOT NULL,
        LEVEL_ID        VARCHAR(50),
        LEVEL_ORDER     VARCHAR(50),
        TEXT_SPEC       VARCHAR(500),
        MIN_LIMIT       VARCHAR(50),
        MAX_LIMIT       VARCHAR(50),
        TYPICAL_TEXT    VARCHAR(50),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_MLP_VIEW PRIMARY KEY (ANALYSIS_ID, COMPONENT_NAME, PRODUCT_ID, PRODUCT_VERSION),
        CONSTRAINT FK_MLP_VIEW_MLP_HEADER FOREIGN KEY (PRODUCT_ID, PRODUCT_VERSION)
            REFERENCES MLP_HEADER ("IDENTITY", PRODUCT_VERSION)
    );

    CREATE TABLE DESTINATION (
        "IDENTITY"      VARCHAR(50)     NOT NULL,
        DESCRIPTION     VARCHAR(200),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_DESTINATION PRIMARY KEY ("IDENTITY")
    );

    CREATE TABLE PHRASE_FORMAT (
        PHRASE_ID       VARCHAR(50)     NOT NULL,
        PHRASE_TYPE     VARCHAR(20)     NOT NULL,
        PHRASE_TEXT     VARCHAR(500),
        SOURCE          VARCHAR(10),
        LAST_UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_PHRASE_FORMAT PRIMARY KEY (PHRASE_ID)
    );
