-- VERSIONED_ANALYSIS (Redshift DW typed table)
-- Deploy order 01/15 (forward FK order).
-- Source of truth: DDL/latest_dll_truth/ALL_TABLES_REDSHIFT.sql

CREATE TABLE VERSIONED_ANALYSIS (
    "IDENTITY"          VARCHAR(50)     NOT NULL,
    ANALYSIS_VERSION    BIGINT          NOT NULL,
    ANALYSIS_ORDER      BIGINT,
    GROUP_ID            VARCHAR(50),
    ANALYSIS_TYPE       VARCHAR(50),
    DESCRIPTION         VARCHAR(200),
    INSTTYPE_ID         VARCHAR(50),
    PREPARATION_ID      VARCHAR(50),
    EXPECTED_TIME       VARCHAR(50),
    CHARGECODE          VARCHAR(50),
    RESULT_SCREEN       VARCHAR(50),
    MODIFIED_ON         VARCHAR(20),
    MODIFIED_BY         VARCHAR(50),
    MODIFIABLE          CHAR(1),
    REMOVEFLAG          CHAR(1),
    CALCULATION         VARCHAR(500),
    REPLICATES          BIGINT,
    ACCESS_FLAGS        BIGINT,
    COMP_REPLICATES     BIGINT,
    GENERIC_ANALYSIS    CHAR(1),
    APPROVAL_REQD       CHAR(1),
    ALLOW_CATEGORY      CHAR(1),
    APPROVAL_STATUS     CHAR(1),
    INSPECTION_PLAN     VARCHAR(50),
    SAMPLING_PLAN_TYPE  VARCHAR(50),
    AUTO_VALIDATE       CHAR(1),
    SHIPPING_FLAG       CHAR(1),
    SOURCE              VARCHAR(10),
    LAST_UPDATED_AT     TIMESTAMP,
    CONSTRAINT PK_VERSIONED_ANALYSIS PRIMARY KEY ("IDENTITY", ANALYSIS_VERSION)
);
