-- VERSIONED_COMPONENT (Redshift DW typed table)
-- Deploy order 02/15 (forward FK order).
-- Source of truth: DDL/latest_dll_truth/ALL_TABLES_REDSHIFT.sql

CREATE TABLE VERSIONED_COMPONENT (
    NAME                VARCHAR(100)    NOT NULL,
    ANALYSIS            VARCHAR(50)     NOT NULL,
    ANALYSIS_VERSION    BIGINT          NOT NULL,
    ORDER_NUMBER        BIGINT,
    RESULT_TYPE         VARCHAR(50),
    UNITS               VARCHAR(50),
    MINIMUM             VARCHAR(50),
    MAXIMUM             VARCHAR(50),
    TRUE_WORD           VARCHAR(50),
    FALSE_WORD          VARCHAR(50),
    ALLOWED_CHARACTERS  VARCHAR(200),
    CALCULATION         VARCHAR(500),
    PLACES              BIGINT,
    REP_CONTROL         VARCHAR(50),
    REPLICATES          VARCHAR(10),
    SIG_FIGS_NUMBER     BIGINT,
    SIG_FIGS_ROUNDING   VARCHAR(50),
    SIG_FIGS_FILTER     VARCHAR(50),
    MINIMUM_PQL         VARCHAR(50),
    MAXIMUM_PQL         VARCHAR(50),
    PQL_CALCULATION     VARCHAR(500),
    FORMULA             VARCHAR(500),
    MATRIX_NO           BIGINT,
    MATRIX_NAME         VARCHAR(50),
    COLUMN_NO           BIGINT,
    COLUMN_NAME         VARCHAR(50),
    ROW_NO              BIGINT,
    ROW_NAME            VARCHAR(50),
    DESCRIPTION         VARCHAR(200),
    DESCRIPTION_CERQFRA VARCHAR(200),
    SOURCE              VARCHAR(10),
    LAST_UPDATED_AT     TIMESTAMP,
    CONSTRAINT PK_VERSIONED_COMPONENT PRIMARY KEY (NAME, ANALYSIS, ANALYSIS_VERSION),
    CONSTRAINT FK_VCOMP_VERSIONED_ANALYSIS FOREIGN KEY (ANALYSIS, ANALYSIS_VERSION)
        REFERENCES VERSIONED_ANALYSIS ("IDENTITY", ANALYSIS_VERSION)
);
