-- MLP_HEADER (Redshift DW typed table)
-- Deploy order 03/15 (forward FK order).
-- Source of truth: DDL/latest_dll_truth/ALL_TABLES_REDSHIFT.sql

CREATE TABLE MLP_HEADER (
    "IDENTITY"      VARCHAR(50)     NOT NULL,
    PRODUCT_GROUP   VARCHAR(50),
    DESCRIPTION     VARCHAR(200),
    TEST_SCHEDULE   VARCHAR(50),
    PRODUCT_STATUS  VARCHAR(50),
    MODIFIED_ON     VARCHAR(20),
    MODIFIED_BY     VARCHAR(50),
    MODIFIABLE      CHAR(1),
    REMOVEFLAG      CHAR(1),
    GROUP_ID        VARCHAR(50),
    PRODUCT_VERSION BIGINT          NOT NULL,
    VERSION_COMMENT VARCHAR(200),
    VERSION_STATUS  VARCHAR(50),
    CREATED_DATE    VARCHAR(20),
    APPROVAL_REQD   CHAR(1),
    APPROVAL_STATUS CHAR(1),
    INSPECTION_PLAN VARCHAR(50),
    DUREE_ARCHI     VARCHAR(50),
    SOURCE          VARCHAR(10),
    LAST_UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_MLP_HEADER PRIMARY KEY ("IDENTITY", PRODUCT_VERSION)
);
