-- MENSUEL (Redshift DW typed table)
-- Deploy order 12/15 (forward FK order).
-- Source of truth: DDL/latest_dll_truth/ALL_TABLES_REDSHIFT.sql

CREATE TABLE MENSUEL (
    IDENT_NUMBER        BIGINT,
    ID_DATE             VARCHAR(20),
    CODE_CONTROLE       VARCHAR(50),
    PRODUIT             VARCHAR(50)     NOT NULL,
    PRODUCT_VERSION     BIGINT          NOT NULL,
    LOCALISATION        VARCHAR(50)     NOT NULL,
    POINT_PRELEVEMENT   VARCHAR(50),
    "ANALYSE"           VARCHAR(50)     NOT NULL,
    MESURE              VARCHAR(100)    NOT NULL,
    ANNUEL              CHAR(1)         NOT NULL,
    NB_MESURE           BIGINT,
    MOYENNE             VARCHAR(50),
    ECART_TYPE          VARCHAR(50),
    ECART_TYPE_BDQ      VARCHAR(50),
    SPEC_MIN            VARCHAR(50),
    SPEC_MAX            VARCHAR(50),
    CIBLE               VARCHAR(50),
    GROUP_ID            VARCHAR(50),
    SOURCE              VARCHAR(10),
    LAST_UPDATED_AT     TIMESTAMP,
    CONSTRAINT PK_MENSUEL PRIMARY KEY ("ANALYSE", PRODUIT, PRODUCT_VERSION, MESURE, LOCALISATION),

    CONSTRAINT FK_MENSUEL_LOCATION FOREIGN KEY (LOCALISATION)
        REFERENCES "LOCATION" ("IDENTITY"),
    CONSTRAINT FK_MENSUEL_CODE_CONTROLE FOREIGN KEY (CODE_CONTROLE)
        REFERENCES CODE_CONTROLE ("IDENTITY")
);
