-- MENSUEL
-- Monthly aggregated results by product, analysis, and control code.
-- ANNUEL = 'F' distinguishes monthly rows from annual (ANNUEL table alias).
CREATE TABLE MENSUEL (
    ANALYSE         VARCHAR2(50)    NOT NULL,
    ANNUEL          CHAR(1)         NOT NULL,   -- 'F' = monthly
    MESURE          VARCHAR2(100)   NOT NULL,
    PRODUIT         VARCHAR2(50)    NOT NULL,
    PRODUCT_VERSION NUMBER(10)      NOT NULL,
    LOCALISATION    VARCHAR2(50)    NOT NULL,
    CODE_CONTROLE   VARCHAR2(50),
    CONSTRAINT PK_MENSUEL PRIMARY KEY (ANALYSE, PRODUIT, PRODUCT_VERSION, MESURE, LOCALISATION),
    CONSTRAINT FK_MENSUEL_VERSIONED_ANALYSIS FOREIGN KEY (ANALYSE) REFERENCES VERSIONED_ANALYSIS (IDENTITY),
    CONSTRAINT FK_MENSUEL_LOCATION FOREIGN KEY (LOCALISATION) REFERENCES LOCATION (IDENTITY),
    CONSTRAINT FK_MENSUEL_CODE_CONTROLE FOREIGN KEY (CODE_CONTROLE) REFERENCES CODE_CONTROLE (IDENTITY),
    CONSTRAINT CHK_MENSUEL_ANNUEL CHECK (ANNUEL = 'F')
);
