-- VERSIONED_COMPONENT
-- Versioned analyte/component definitions linked to a specific analysis version.
-- Composite PK: NAME + ANALYSIS + ANALYSIS_VERSION.
CREATE TABLE VERSIONED_COMPONENT (
    NAME                VARCHAR2(100)   NOT NULL,
    ANALYSIS            VARCHAR2(50)    NOT NULL,
    ANALYSIS_VERSION    NUMBER(10)      NOT NULL,
    CONSTRAINT PK_VERSIONED_COMPONENT PRIMARY KEY (NAME, ANALYSIS, ANALYSIS_VERSION),
    CONSTRAINT FK_VCOMP_VERSIONED_ANALYSIS FOREIGN KEY (ANALYSIS, ANALYSIS_VERSION)
        REFERENCES VERSIONED_ANALYSIS (IDENTITY, ANALYSIS_VERSION)
);
