-- VERSIONED_ANALYSIS
-- Versioned analysis method definitions.
-- Composite PK: IDENTITY + ANALYSIS_VERSION.
CREATE TABLE VERSIONED_ANALYSIS (
    IDENTITY            VARCHAR2(50)    NOT NULL,
    ANALYSIS_VERSION    NUMBER(10)      NOT NULL,
    CONSTRAINT PK_VERSIONED_ANALYSIS PRIMARY KEY (IDENTITY, ANALYSIS_VERSION)
);
