-- MLP_HEADER
-- Product / MLP (Material/Product) header records.
-- Composite PK: IDENTITY + PRODUCT_VERSION.
CREATE TABLE MLP_HEADER (
    IDENTITY        VARCHAR2(50)    NOT NULL,
    PRODUCT_VERSION NUMBER(10)      NOT NULL,
    CONSTRAINT PK_MLP_HEADER PRIMARY KEY (IDENTITY, PRODUCT_VERSION)
);
