-- MLP_VIEW
-- Material/product limit plan view: links analysis, component, and product with their limits.
-- Joined with outer joins (+), so acts as an optional enrichment table.
CREATE TABLE MLP_VIEW (
    ANALYSIS_ID     VARCHAR2(50)    NOT NULL,
    COMPONENT_NAME  VARCHAR2(100)   NOT NULL,
    PRODUCT_ID      VARCHAR2(50)    NOT NULL,
    PRODUCT_VERSION NUMBER(10)      NOT NULL,
    CONSTRAINT PK_MLP_VIEW PRIMARY KEY (ANALYSIS_ID, COMPONENT_NAME, PRODUCT_ID, PRODUCT_VERSION),
    CONSTRAINT FK_MLP_VIEW_VERSIONED_ANALYSIS FOREIGN KEY (ANALYSIS_ID)
        REFERENCES VERSIONED_ANALYSIS (IDENTITY),
    CONSTRAINT FK_MLP_VIEW_MLP_HEADER FOREIGN KEY (PRODUCT_ID, PRODUCT_VERSION)
        REFERENCES MLP_HEADER (IDENTITY, PRODUCT_VERSION)
);
